### ISSUE TITLE
Sometimes fkill returns before a process is no longer visible

### ISSUE THREAD

**Issue by AlexTes** [sindresorhus/fkill#10]
I've seen three separate tests fail because of this now. Perhaps fkill needs smarter process exists checking. There doesn't seem to be a way to improve `process-exists` from what I read. I'll leave this here for voting.

**Comment by AlexTes** [comment]
Just saw it happen on [this](https://travis-ci.org/sindresorhus/fkill/jobs/214431260) Travis build too.

**Comment by AlexTes** [comment]
Builds are failing regularly. I'm quite sure this is the issue. I'm going to try adding a 100ms delay.

**Comment by Autre31415** [comment]
This quirk is still something that can be witnessed at a consumer level.

It might be worth the addition of a confidence checker timeout similar to what [ps-node uses in its kill method](https://github.com/neekey/ps/blob/b022882a0cc9344c7c66c47301b27910235078e3/lib/index.js#L220), but perhaps with a shorter timer.

**Comment by alextes** [comment]
@Autre31415 I'd say add an upvote, or maybe even open a new issue. This was an issue with fkill's tests. Users don't seem to care much.

You could also consider creating a new issue suggesting a PR, I think something as simple as polling for the process to die for a second or three could be an improvement.
