### ISSUE TITLE
Adding an ignoreCase option

### ISSUE THREAD

**Issue by AlexTes** [sindresorhus/fkill#11]
I started work on adding an ignoreCase option.
First of all, that was a fun trail down the chain to find out how `fkill` and its dependencies work. I quickly stopped searching the npm registry for them and searching Sindre's personal repo's instead 😄 .
Secondly: the fkill logo is _beautiful_. Had to be said.
Third: adding an ignoreCase option turns out to be a real pain.

**Linux**
Easy. [Add '-I' flag](https://linux.die.net/man/1/killall). Done. Go Linux.

**macOS and BSD**
No ignore case option. The closest provided option is using a regular expression 😓 .
Both do however have `pgrep` and `pkill`, both of which, feature an ignore case option!

**SunOS**
What even is this 😂 ? Anyway [not even a little bit of options](http://www.manpages.info/sunos/killall.1.html)

**Windows**
[Zero options](https://ss64.com/nt/taskkill.html) to ignore case, zero options to [collect pid's](https://ss64.com/nt/tasklist.html) with ignore case.

We could just issue two kill commands.. Far easier. Less correct.

Please let me loose on this :3 . If you say, _far_ too much hassle for ignore case, don't want to complicate the code that bad, or take on an abstraction for it .. I totally understand.

**Comment by sindresorhus** [comment]
How about this:

- Linux: `killall` with `-I` flag
- macOS: `pkill` with the `-x` flag to ensure we only kill exact matches case insensitively
- Windows: Use [`tasklist`](https://github.com/sindresorhus/tasklist) to get the processes and then filter case insensitively in JS.
- SunOS: Don't care.

**Comment by MarkTiedemann** [comment]
**Windows**
Easy. Already case insensitive by default, no option needed. Go Windows.

🙃
