### ISSUE TITLE
Why is the 'fail' test not executed on windows?

### ISSUE THREAD

**Issue by AlexTes** [sindresorhus/fkill#16]

**Comment by sindresorhus** [comment]
I don't know. I think it was a mistake in https://github.com/sindresorhus/fkill/commit/d39b693862c3d8282d2771ff4904c2693e81fcee

**Comment by AlexTes** [comment]
Let's find out!

**Comment by AlexTes** [comment]
@sindresorhus so the test definitely fails on windows. The only question now is would you like `taskkill` to throw when a process is not found, or linux to not throw when a process is not found?

**Comment by sindresorhus** [comment]
> The only question now is would you like taskkill to throw when a process is not found

Yes, silent fail is never good.

**Comment by AlexTes** [comment]
I agree. I'll dive right in 🏊.
Have a great day @sindresorhus!

p.s. A monkey. Who would've thought?
