### ISSUE TITLE
Don't fail fast

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/fkill#2]
Currently, if one child process fails, it finishes. This can make it hard for the user to know which failed and not. It should wait until all are complete, gather up all the errors and display them at the end.

**Comment by kevva** [comment]
In the CLI or both? And should we gather them in an array then or what?

**Comment by sindresorhus** [comment]
Both. One error with multiple lines.

**Comment by kevva** [comment]
Alright, one big ass error with the stacks too? :)

**Comment by sindresorhus** [comment]
@kevva No stack needed really, as the error is external.
