### ISSUE TITLE
Global install

### ISSUE THREAD

**Issue by mathiasrw** [sindresorhus/fkill#48]
Absolutely love fkill. Use it all the time. 

I understand the reasons behind making a seperate fkill-cli repo for CLI - but it means that is not as smooth to type. 

Would you be willing to accept a PR adding a bin named fkill pointing to basically what would be the content of https://github.com/sindresorhus/fkill-cli/blob/main/cli.js but using to the local version of the fkill code?

so you could do a `npx fkill :8080` instead of having to remember the -cli. 

I know, I know - it might seem silly, but fkill is kind of those commands that just sits in the fingers.

**Comment by sindresorhus** [comment]
The recommended way is to just install it globally. It's then even shorter to type: `fkill :8080`. I'm not interested in adding extra stuff just to make the `npx` experience 4 characters shorter to type. If you insist on using `npx`, you could just use a shell alias: `alias fkill='npx fkill-cli'`.
