### ISSUE TITLE
Cannot find module node:process

### ISSUE THREAD

**Issue by IbrahimSam96** [sindresorhus/fkill#58]
Hey I have a express app that runs on :6001 when window_open listener triggers in a electron application. How can i solve for this error?

![NodeProcess Error](https://user-images.githubusercontent.com/72482204/157332252-c62eae7b-8013-46e6-aa3b-85b771fb0981.PNG)

**Comment by sindresorhus** [comment]
This is a problem with Webpack or your Webpack config. `node:process` is totally valid import in Node.js.
