### ISSUE TITLE
Unexpected behavior because of pkill on macOS

### ISSUE THREAD

**Issue by pzich** [sindresorhus/fkill#60]
For `macosKill`, the `killByName` option uses `pkill` instead of `killall`.

This causes unexpected behavior, because `pkill` kills all processes matching a pattern instead of an exact process string match.

For example, calling `fkill('something')` on macOS will kill `something` processes, but also `something-else`, `not-something`, etc. as a standard string "pattern" is actually a substring match.

**Comment by sindresorhus** [comment]
Looks like `pkill` was introduced in https://github.com/sindresorhus/fkill/commit/e47f459f3b5c768df76ff16bd6d23664dc657e4f

I did actually comment to make sure to use exact matching in https://github.com/sindresorhus/fkill/issues/11#issuecomment-285856165, but it was missed in the pull request:

> macOS: pkill with the -x flag to ensure we only kill exact matches case insensitively
